#!/usr/bin/env python3

import sys
from PyPDF2 import PdfFileReader, PdfFileWriter
from PyPDF2.pdf import PageObject

WIDTH = 580
MARGIN = 100

filename = sys.argv[1][:-4]

with open(filename + ".pdf", 'rb') as f:
    pdf = PdfFileReader(f)

    p = pdf.getPage(1)
    w = p.mediaBox.getWidth()
    scale = float(WIDTH / w)

    pdf_writer = PdfFileWriter()

    for i in range(pdf.getNumPages()):
        page = pdf.getPage(i)
        page.scale(scale, scale)

        h = page.mediaBox.getHeight()
        padded_page = PageObject.createBlankPage(pdf, WIDTH + MARGIN, h)

        padded_page.mergeTranslatedPage(page, 0, 0)

        pdf_writer.addPage(padded_page)

    with open("scaled/" + filename + "_scaled.pdf", "wb") as output_pdf:
        pdf_writer.write(output_pdf)
